"""
scrape_ferns.py
───────────────
Scrapes plant data from https://tropical.theferns.info for a list of species
and saves the results to ferns_data.json, ready to be imported into Barakah Roots.

Usage:
    pip install requests beautifulsoup4
    python scrape_ferns.py

Edit SPECIES_LIST below with the species you want.
Results are saved to ferns_data.json in the same directory.
"""

import json
import time
import requests
from bs4 import BeautifulSoup

# ── Configure your species here ───────────────────────────────────────────────
SPECIES_LIST = [
    "Abrus schimperi",
    "Acacia farnesiana",
    "Acacia nilotica subsp. tomentosa",
    "Acacia polyacantha",
    "Acacia sieberiana",
    "Acacia species",
    "Achillea ligustica",
    "Achyranthes aspera",
    "Adhatoda vasica",
    "Afraegle paniculata",
    "Agelanthus brunneus",
    "Ajuga remota",
    "Albizia adianthifolia",
    "Albizia coriaria",
    "Albizia glaberrima",
    "Albizia schimperiana",
    "Alchornea cordifolia",
    "Alchornea laxiflora",
    "Alkanna orientalis",
    "Allanblackia floribunda",
    "Allium myrianthum",
    "Aloe arborescens",
    "Aloe barbadensis",
    "Aloe behana",
    "Aloe berhana",
    "Aloe dawei",
    "Aloe graminicola",
    "Aloe megalacantha",
    "Aloe pulcherrima",
    "Aloe rabaiensis",
    "Aloe rivae",
    "Aloe saponaria",
    "Aloe scabrifolia",
    "Aloe secundiflora",
    "Aloe sinkatana",
    "Aloe species",
    "Aloe turkanensis",
    "Alpinia officinarum",
    "Amaracus akhdarensis",
    "Amaracus pampanini",
    "Ammi majus",
    "Ammi visnaga",
    "Ammodaucus leucotrichus",
    "Anastatica hierochuntica",
    "Ancistrocladus ileboensis",
    "Ancistrocladus likoko",
    "Ancistrocladus robertsoniorum",
    "Angylocalyx oligophyllus",
    "Anonidium mannii",
    "Anthemis tigrensis",
    "Antidesma chevalieri",
    "Antidesma venosum",
    "Antrocaryon klaineanum",
    "Anvillea radiata",
    "Apis mellifica",
    "Apis species",
    "Apium graveolens",
    "Araliopsis soyauxii",
    "Araucaria bidwillii",
    "Arbutus unedo",
    "Argania spinosa",
    "Artabotrys modestus ssp. macranthus",
    "Artemisia arborescens",
    "Artemisia argentea",
    "Artemisia campestris",
    "Artemisia dracunculus",
    "Artemisia herba",
    "Artemisia herba-alba",
    "Artemisia ifranensis",
    "Artemisia judaica",
    "Artemisia mesatlantica",
    "Artemisia monosperma",
    "Artemisia reptans",
    "Artocarpus communis",
    "Aspergillus amstelodami",
    "Asphodelus microcarpus",
    "Aspilia mossambicensis",
    "Aspilia pluriseta",
    "Aspilia species (From Africa)",
    "Asteriscus graveolens",
    "Astragalus armatus",
    "Astragalus peregrinus",
    "Atractylis flava",
    "Azolla nilotica",
    "Babcockia platylepsis",
    "Baillonella toxisperma",
    "Balanites aegyptiaca",
    "Bassia indica",
    "Bassia muricata",
    "Beauveria bassiana",
    "Bignonia binata",
    "Bolusanthus speciosus",
    "Bombax malabaricum",
    "Borago officinalis",
    "Bos indicus",
    "Boswellia carterii",
    "Boswellia neglecta",
    "Boswellia papyrifera",
    "Boswellia species",
    "Brassica oleracea",
    "Brickellia coulteri",
    "Brocchia cinerea",
    "Bulbine abyssinica",
    "Bulbine capitata",
    "Bulbine frutescens",
    "Bunium incrassatum",
    "Bupleurum fruticosum",
    "Bupleurum montanum",
    "Bupleurum plantagineum",
    "Caesalpinia volkensii",
    "Calendula officinalis",
    "Calodendrum capense",
    "Campylospermum calanthum",
    "Campylospermum mannii",
    "Capparis spinosa",
    "Carissa edulis",
    "Carthamus mareoticus",
    "Carya illinoinensis",
    "Casimiroa edulis",
    "Cassia floribunda",
    "Cassia obtusifolia",
    "Cassipourea congoensis",
    "Cedrelopsis grevei",
    "Cedrus atlantica",
    "Celtis africana",
    "Centaurea africana",
    "Centaurea alexandrina",
    "Centaurea calcitrapa",
    "Centaurea furfuracea",
    "Centaurea glomerata",
    "Centaurea incana",
    "Centaurea maroccana",
    "Centaurea omphalotricha",
    "Centaurea pallescens",
    "Chaetomium sp.",
    "Cheirolophus uliginosus",
    "Chenopodium album",
    "Chenopodium murale",
    "Chiliadenus montanus",
    "Chrozophora oblongifolia",
    "Chrozophora species",
    "Chrozophora tinctoria",
    "Chrysanthemum coronarium",
    "Chrysanthemum macrocarpum",
    "Chrysanthemum viscidehirtum",
    "Chythrantus claneianus",
    "Cineraria abyssinica",
    "Cistus libanotis",
    "Citrus aurantium",
    "Citrus nobilis x Citrus deliciosa",
    "Citrus reticulata",
    "Cleistochlamys kirkii",
    "Cleome droserifolia",
    "Cleome paradoxa",
    "Cleome species",
    "Clerodendrum eriophyllum",
    "Coffea canephora",
    "Combretum dolichopetalum",
    "Combretum molle",
    "Combretum racemosum",
    "Commiphora confusa",
    "Commiphora kua",
    "Commiphora molmol",
    "Commiphora quadricincta",
    "Conyza aegyptiaca",
    "Conyza bonariensis",
    "Conyza dioscoridis",
    "Conyza newii",
    "Conyza pyrrhopappa",
    "Conyza steudellii",
    "Conyza stricta",
    "Cordia millenii",
    "Coriandrum sativum",
    "Cotoneaster orbicularis",
    "Cotula cinerea",
    "Crataegus azarolus",
    "Crataegus oxyacantha",
    "Crataegus sinaica",
    "Crateva adansonii",
    "Crinum augustum",
    "Crinum bulbispermum",
    "Croton alienus",
    "Croton macrostachys",
    "Croton macrostachyus",
    "Croton megalocarpoides",
    "Croton oligandrus",
    "Croton sylvaticus",
    "Croton zambesicus",
    "Croton zambiescus",
    "Cupressus arizonica",
    "Cupressus dupreziana",
    "Cupressus sempervirens",
    "Curcuma longa",
    "Curya pecan",
    "Cussonia bancoensis",
    "Cussonia holstii",
    "Cymbopogon schoenanthus",
    "Cynara scolymus",
    "Cyperus rotundus",
    "Dacryodes edulis",
    "Dalbergia melanoxylon",
    "Daucus carota subsp. carota",
    "Daucus carota subsp. maritimus",
    "Daucus glaber",
    "Derris trifoliata",
    "Desbordesia glaucescens",
    "Descurainia sophia",
    "Desmodium uncinatum",
    "Desmostachya bipinnata",
    "Dialium excelsum",
    "Dioscorea species",
    "Diospyros crassiflora",
    "Diospyros mespiliformis",
    "Diplotaxis acris",
    "Diplotaxis harra",
    "Discoglypremna caloneura",
    "Dodonaea angustifolia",
    "Dodonaea viscosa",
    "Dorstenia dinklagei",
    "Dorstenia kameruniana",
    "Dorstenia mannii",
    "Dorstenia poinsettiifolia",
    "Dracaena mannii",
    "Drypetes armoracia",
    "Drypetes gerrardii",
    "Drypetes molunduana",
    "Drypetes tessmanniana",
    "Echinops galalensis",
    "Echium sericeum",
    "Ekebergia benguelensis",
    "Ekebergia capensis",
    "Ekebergia senegalensis",
    "Elaeophorbia drupifera",
    "Embelia schimperi",
    "Entada rheedei",
    "Ephedra alata",
    "Ephedra aphylla",
    "Epilobium hirsutum",
    "Eragrostis tef",
    "Erica mannii",
    "Erigeron floribundus",
    "Erodium crassifolium",
    "Erodium oxyrrhynchum subsp. oxyrrhynchum",
    "Erucaria microcarpa",
    "Erythrina abyssinica",
    "Erythrina addisoniae",
    "Erythrina burttii",
    "Erythrina caffra",
    "Erythrina lysistemon",
    "Erythrina sacleuxii",
    "Erythrina schliebenii",
    "Erythrina senegalensis",
    "Escinops ellenbeckii",
    "Eucalyptus cinerea",
    "Eucalyptus globulous maidenii",
    "Eucalyptus occidentalis",
    "Eucalyptus odorata",
    "Euclea divinorum",
    "Eugenia jambolana",
    "Euphorbia bupleuroides",
    "Euphorbia gaditana",
    "Euphorbia helioscopia",
    "Euphorbia retusa",
    "Euphorbia sanctae-catharinae",
    "Euphorbia species",
    "Fagara heitzii",
    "Fagara tessmannii",
    "Ferula longipes",
    "Ferula lutea",
    "Ficus auriculata",
    "Ficus barteri",
    "Ficus bubu",
    "Ficus carica",
    "Ficus exasperata",
    "Ficus glumosa",
    "Ficus lingua",
    "Ficus mucuso",
    "Ficus natalensis",
    "Ficus sansibarica",
    "Ficus saussureana",
    "Ficus sur",
    "Ficus sycomorus",
    "Ficus thonningii",
    "Ficus vallis-choudae",
    "Ficus variifolia",
    "Foeniculum vulgare",
    "Francoeuria crispa",
    "Fraxinus oxycarba",
    "Friesodielsia obovata",
    "Fuerstia africana",
    "Gaillardia aristata",
    "Galega battiscombei",
    "Galega lindblomi",
    "Garcinia edulis",
    "Gardenia ternifolia",
    "Geosmithia langdonii",
    "Gladiolus segetum",
    "Globimetula dinklagei",
    "Glyphaea brevis",
    "Gnidia involucrata",
    "Gomphocarpus sinaicus",
    "Gossypium barbadense",
    "Gutenbergia cordifolia",
    "Gynandropsis gynandra",
    "Haematococcus pluvialis",
    "Halimium halimifolium",
    "Haplophyllum tuberculatum",
    "Harpephyllum caffrum",
    "Helianthemum sessiliflorum",
    "Helichrysum stoechas",
    "Hibiscus noldeae",
    "Hugonia castaneifolia",
    "Hydnora johannis",
    "Hypericum ericoides ssp. Roberti",
    "Hypericum humifusum",
    "Hypericum perfoliatum",
    "Hypericum perforatum",
    "Hypericum quartinianum",
    "Hypericum riparium",
    "Hypericum tomentosum",
    "Hyphaene thebaica",
    "Hypocrea lixii",
    "Ifloga labillardieri",
    "Ifloga spicata",
    "Inga edulis Mart",
    "Inula crithmoides",
    "Iphiona scabra",
    "Jacaranda mimosaefolia",
    "Jasonia candicans",
    "Jasonia montana",
    "Jatropha multifida",
    "Joannesia princeps",
    "Juglans regia",
    "Juglans regia L",
    "Juniperus phoenicea",
    "Juniperus species",
    "Justicia secunda",
    "Kigelia africana",
    "Klainedoxa gabonensis",
    "Kniphofia foliosa",
    "Kniphofia reflexa",
    "Kniphofia species",
    "Kobus ellipsiprymnus",
    "Lactuca sativa",
    "Lagerstroemia indica",
    "Lannea alata",
    "Lannea schimperi",
    "Lantana montevidensis",
    "Lantana viburnoides sp viburnoides var kisi",
    "Launaea arborescens",
    "Launaea resedifolia",
    "Lavandula multifida",
    "Laxitextum incrustatum",
    "Leptadenia arborea",
    "Leucas aspera",
    "Leucas inflata",
    "Leucas martinicensis",
    "Liatris spicata",
    "Limoniastrum guyonianum",
    "Limonium axillare",
    "Lippia javanica",
    "Lippia ukambensis",
    "Livistona australis",
    "Ludwigia leptocarpa",
    "Madia anomala",
    "Madia capitata",
    "Madia dissitiflora",
    "Maesa lanceolata",
    "Mangifera indica",
    "Manihot esculenta",
    "Manilkara obovata",
    "Marrubium deserti",
    "Matricaria pubescens",
    "Matthiola livida",
    "Melaleuca ericifolia",
    "Melaleuca quinquenervia",
    "Melia azedarach",
    "Melia volkensii",
    "Mentha pulegium",
    "Microglossa pyrifolia",
    "Milletia dura",
    "Millettia duchesnei",
    "Millettia dura",
    "Millettia ferruginea",
    "Millettia griffoniana",
    "Millettia lasiantha",
    "Millettia leucantha",
    "Millettia macrophylla",
    "Millettia micans",
    "Millettia oblata",
    "Millettia usaramensis usaramensis",
    "Mitragyna inermis",
    "Mkilua fragrans",
    "Monanthotaxis littoralis",
    "Monanthotaxis trichocarpa",
    "Mondia whytei",
    "Monotes kerstingii",
    "Morella salicifolia",
    "Moringa oleifera",
    "Morus mesozygia",
    "Mundulea sericea",
    "Mussaenda luteola",
    "Myrica arborea",
    "Myrsine africana",
    "Neoboutonia macrocalyx",
    "Neorautanenia mitis",
    "Newbouldia laevis",
    "Nigrospora sphaerica",
    "Nitraria retusa",
    "Nymphaea lotus",
    "Ochna holstii",
    "Ocimum kenyense",
    "Ocimum kilimandscharicum",
    "Oligomeris linifolia",
    "Omphalocarpum elatum",
    "Oncoba spinosa",
    "Ononis angustissima",
    "Ononis natrix",
    "Opuntia dillenii",
    "Ormocarpum kirkii",
    "Ormocarpum sennoides",
    "Otanthus maritimus",
    "Oxyanthus unilocularis",
    "Ozoroa insignis",
    "Pallenis spinosa",
    "Pancratium maritimum",
    "Parkinsonin aculeata",
    "Parmentiera cereifera",
    "Paullinia pinnata",
    "Penicillium citrinum",
    "Pentadesma butyracea",
    "Pentas bussei",
    "Pentas lanceolata",
    "Pentas longiflora",
    "Pentas parvifolia",
    "Pentas schimperi",
    "Pentzia albida",
    "Pergularia tomentosa",
    "Periploca laevigata",
    "Perralderia coronopifolia",
    "Petroselinum crispum",
    "Phyllanthus emblica",
    "Pistacia atlantica",
    "Pistacia chinensis",
    "Pistacia khinjuk",
    "Pistacia lentiscus",
    "Pituranthos scoparius",
    "Pituranthos triradiatus",
    "Platycelyphium voënse",
    "Plectranthus alpinus",
    "Plectranthus glandulosus",
    "Plectranthus marrubioides",
    "Plumeria rubra",
    "Polyalthia longifolia",
    "Polygonum limbatum",
    "Polygonum senegalense",
    "Prosopis juliflora",
    "Pseudocedrela kotschyi",
    "Pseudognaphalium luteo-album",
    "Pseudospondias microcarpa",
    "Psiadia punctulata",
    "Psidium guajava",
    "Pteranthus dichotomus",
    "Pulicaria laciniata",
    "Pulicaria undulata",
    "Punica granatum",
    "Pycnanthus anglonensis",
    "Pycnanthus angolensis",
    "Quercus ilex",
    "Quercus suber",
    "Randonia africana",
    "Rapanea melanophloes",
    "Rapanea melanphloes",
    "Rauvolfia caffra",
    "Reaumuria vermiculata",
    "Reichardia tingitana",
    "Retama raetam",
    "Rhabdophyllum arnoldianum",
    "Rhamnus alaternus",
    "Rhamnus disperma",
    "Rhamnus prinoides",
    "Rhus natalensis",
    "Rhus pyroides",
    "Rhus retinorrhoea",
    "Rorippa palustris",
    "Rosmarinuseriocalyx",
    "Rothmannia talbotii",
    "Rumex abysinica",
    "Rumex abysinicus",
    "Rumex abyssinicus",
    "Rumex bequaerrii",
    "Rumex crispus",
    "Rumex ruwenzoriensis",
    "Rumex usambarensis",
    "Salia triloba",
    "Salix subserrata",
    "Salvia jaminiana",
    "Salvia lanigera",
    "Salvia palaestina",
    "Salvia triloba",
    "Sanghuangporus sp.",
    "Sanguisorba minor",
    "Sarcocephalus pobeguinii",
    "Schinus molle",
    "Schizozygia coffaeoides",
    "Schouwia thebaica",
    "Scrophularia saharae",
    "Securidaca longepedunculata",
    "Securidaca longipedunculata",
    "Senecio angulatus",
    "Senecio gallicus",
    "Senecio hoggariensis",
    "Senecio roseiflorus",
    "Senecio ruwenzoriensis",
    "Senecio schweinfurthii",
    "Senna alata",
    "Senna didymobotrya",
    "Senna floribunda",
    "Senna italica",
    "Senna multiglandulosa",
    "Senna septemtrionalis",
    "Senna sophera",
    "Sida spinosa",
    "Silybum marianum",
    "Siphonochilus aethiopicus",
    "Sisymbrium irio",
    "Solanum aculeastrum",
    "Solenostemma argel",
    "Sonchus arvensis",
    "Sonchus brachyotus",
    "Sonchus fauces-orci",
    "Sonchus gandogeri",
    "Sonchus gomerensis",
    "Sonchus gummifer",
    "Sonchus lidii",
    "Sonchus luxurians",
    "Sonchus macrocarpus",
    "Sonchus melanolepis",
    "Sonchus nanus",
    "Sonchus pinnatifidus",
    "Sonchus radicatus",
    "Sonchus schweinfurthii",
    "Sphaeranthus bullatus",
    "Sphaerocoryne gracilis",
    "Stachys mialhesi",
    "Staudtia kamerunensis",
    "Stereospermum zenkeri",
    "Stuhlmannia moavi",
    "Swietenia mahogani",
    "Symphonia globulifera",
    "Synaptolepis kirkii",
    "Syncerus caffer",
    "Syzygium cumini",
    "Syzygium grande",
    "Syzygium samarangense",
    "Tabebuia argentea",
    "Tabernaemontana contorta",
    "Taeckholmia canariensis",
    "Taeckholmia capillaris",
    "Taeckholmia heterophylla",
    "Taeckholmia microcarpa",
    "Taeckholmia regis-jubae",
    "Tagetes minuta",
    "Tamarix balansae",
    "Tamarix nilotica",
    "Tarchonanthus camphoratus",
    "Taverniera abyssinica",
    "Teclea gerrardii",
    "Teclea natalensis",
    "Teclea nobilis",
    "Teclea simplicifolia",
    "Teclea trichocarpa",
    "Tectona grandis",
    "Tephrosia apollinea",
    "Tephrosia elata",
    "Tephrosia purpurea",
    "Tephrosia rhodesica",
    "Tephrosia villosa",
    "Tephrosia vogelii",
    "Terminalia arjuna",
    "Terminalia brownii",
    "Terminalia ivorensis",
    "Terminalia mantaly",
    "Terminalia sericeae",
    "Terminalia species",
    "Tetracera potatoria",
    "Tetraclinis articulata",
    "Tetradenia riparia",
    "Teucrium barbeyanum",
    "Teucrium leucocladum",
    "Teucrium polium subsp. polium",
    "Teucrium scorodonia L. subsp. baeticum",
    "Thalassia hemprichii",
    "Thespesia garckeana",
    "Thymelaea hirsuta",
    "Thymus broussonetii",
    "Thymus broussonetti",
    "Thymus maroccanus",
    "Toddalia asiatica",
    "Torilis radiata",
    "Tribulus alatus",
    "Tribulus pentandrus",
    "Tribulus terrestris",
    "Trichilia monadelpha",
    "Trichodesma africanum",
    "Tridesmostemon omphalocarpoides",
    "Turraea floribunda",
    "Turraea nilotica",
    "Turraea parvifolia",
    "Turraea robusta",
    "Turraea wakefieldii",
    "Turraeanthus africanus",
    "Turraeanthus mannii",
    "Uvaria dependens",
    "Uvaria lucida ssp. lucida",
    "Uvaria pandensis",
    "Uvaria scheffleri",
    "Uvaria species",
    "Vepris glomerata",
    "Vepris lecomteana",
    "Vepris uguenensis",
    "Verbascum atlanticum",
    "Vernonia auriculifera",
    "Vernonia brachycalyx",
    "Vernonia guineensis",
    "Vernonia urticifolia",
    "Viburnum tinus",
    "Vismia laurentii",
    "Warburgia stuhlmannii",
    "Warburgia ugandensis",
    "Warionia saharae",
    "Withania adpressa",
    "Zanthoxylum chalybeum",
    "Zanthoxylum gilletii",
    "Zanthoxylum leprieurii",
    "Zanthoxylum paracanthum",
    "Zanthoxylum usambarense",
    "Ziziphus spina-christi",
    # Add more species names here...
]

OUTPUT_FILE = "ferns_data.json"
BASE_URL    = "https://tropical.theferns.info/viewtropical.php"
DELAY_SEC   = 1.5   # polite delay between requests


# ── Scraper ───────────────────────────────────────────────────────────────────
def clean(text):
    """Strip whitespace and remove citation bracketed numbers like [303]."""
    import re
    text = re.sub(r'\[\d+\]', '', text)
    return ' '.join(text.split()).strip()


def scrape_species(name):
    """Fetch and parse one species page. Returns a dict of extracted fields."""
    url = BASE_URL + "?id=" + name.replace(" ", "+")
    try:
        resp = requests.get(url, timeout=15, headers={"User-Agent": "Mozilla/5.0"})
        resp.raise_for_status()
    except requests.RequestException as e:
        print(f"  ✗ Network error for {name}: {e}")
        return None

    soup = BeautifulSoup(resp.text, "html.parser")

    result = {
        "species":      name,
        "url":          url,
        "common_names": [],
        "family":       "",
        "description":  "",
        "uses":         "",
        "habitat":      "",
        "distribution": "",
        "preparation":  "",
        "edibility":    "",
        "medicinal":    "",
    }

    # ── Common names ──────────────────────────────────────────────────────────
    # Appears as "Common Name: X" in the page
    for tag in soup.find_all(["h4", "p", "div"]):
        txt = tag.get_text(" ", strip=True)
        if txt.lower().startswith("common name"):
            names = txt.split(":", 1)[-1].strip()
            result["common_names"] = [n.strip() for n in names.split(",") if n.strip()]
            break

    # ── Family ────────────────────────────────────────────────────────────────
    for tag in soup.find_all("h4"):
        txt = tag.get_text(strip=True)
        # Family names are typically one word ending in -aceae or -eae
        import re
        if re.match(r'^[A-Z][a-z]+aceae$', txt) or re.match(r'^[A-Z][a-z]+eae$', txt):
            result["family"] = txt
            break

    # ── Section content ───────────────────────────────────────────────────────
    # The page is structured as <h3>Section Title</h3> followed by <p> tags
    section_map = {
        "general information": "description",
        "known hazards":       None,           # skip
        "edible uses":         "edibility",
        "medicinal uses":      "medicinal",
        "other uses":          "uses",
        "habitat":             "habitat",
        "range":               "distribution",
        "cultivation details": None,           # skip
        "propagation":         None,           # skip
    }

    current_section = None
    for tag in soup.find_all(["h3", "p"]):
        if tag.name == "h3":
            heading = tag.get_text(strip=True).lower()
            current_section = section_map.get(heading)
        elif tag.name == "p" and current_section:
            text = clean(tag.get_text(" ", strip=True))
            if text and len(text) > 20:
                if result[current_section]:
                    result[current_section] += " " + text
                else:
                    result[current_section] = text

    # ── Derive preparation from medicinal + edibility ─────────────────────────
    # Combine relevant sections into a human-readable preparation note
    prep_parts = []
    if result["medicinal"]:
        prep_parts.append(result["medicinal"])
    if result["edibility"]:
        prep_parts.append(result["edibility"])
    result["preparation"] = " ".join(prep_parts)

    # Trim long texts to a sensible length for display
    for key in ("description", "uses", "habitat", "distribution", "preparation",
                "edibility", "medicinal"):
        if len(result[key]) > 1200:
            result[key] = result[key][:1200].rsplit(" ", 1)[0] + "…"

    return result


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    results = {}
    total = len(SPECIES_LIST)

    for i, name in enumerate(SPECIES_LIST, 1):
        print(f"[{i}/{total}] Scraping {name}…")
        data = scrape_species(name)
        if data:
            results[name] = data
            print(f"  ✓ Got: description={bool(data['description'])}, "
                  f"medicinal={bool(data['medicinal'])}, "
                  f"common_names={data['common_names']}")
        else:
            print(f"  ✗ Skipped {name}")

        if i < total:
            time.sleep(DELAY_SEC)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    print(f"\n✅ Done. {len(results)}/{total} species saved to {OUTPUT_FILE}")
    print("\nTo import into Barakah Roots, run:")
    print("    python import_to_barakah.py")


if __name__ == "__main__":
    main()